openapi: '3.0.2'
info:
  title: Cumulus API
  version: '0.8.0'
servers:
  - url: 'https://cumulus-api.rsgis.dev'
    description: Stable API
  - url: 'https://develop-cumulus-api.rsgis.dev'
    description: Development API


components:
  schemas:
    empty_object:
      type: object
    tag:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
        color:
          type: string
    tags:
      type: array
      items:
        $ref: "#/components/schemas/tag"
paths:
  /tags:
    get:
      description: List All Tags
      responses:
        '200':
          description: Array of Tags
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/tags"

    post:
      description: Create a Tag
      responses:
        '201':
          description: A Single Tag
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/tag"
    put:
      description: Update a Tag
      responses:
        '200':
          description: A Single Tag
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/tag"
    delete:
      description: Delete a Tag
      responses:
        '200':
          description: Empty Object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/empty_object"

