#!/bin/bash

# set the COMPOSE_FILE env var
COMPOSE_FILE=docker-compose.yml

dc="docker compose"

while true; do
    case "$1" in
    minio) # adds docker-compose.minio.yml COMPOSE_FILE env var
        echo "Addin minio yaml file"
        COMPOSE_FILE=$COMPOSE_FILE:docker-compose.minio.yml
        shift
        ;;
    geoinit) # adds docker-compose.geoinit.yml to COMPOSE_FILE env var
        echo "Addin geoinit yaml file"
        COMPOSE_FILE=$COMPOSE_FILE:docker-compose.geoinit.yml
        shift
        ;;
    up) # 'up' option
        dc="$dc up"
        shift
        ;;
    down) # 'down' option
        dc="$dc down"
        shift
        ;;
    --build) # --build option
        dc="$dc --build"
        shift
        ;;
    help) # this message
        echo "$0 usage:" && grep .\)\ # $0; printf "\nexample: ./dcompose up --build minio geoinit\n"; exit 0
        ;;
    *)
        break
        ;;
    esac
done

export COMPOSE_FILE

# echo $dc
eval "$dc"
