networks:
  default:
    name: cumulus-api_default

services: 
  minio:
    # image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    image: minio/minio
    environment:
      - MINIO_ROOT_USER=AKIAIOSFODNN7EXAMPLE
      - MINIO_ROOT_PASSWORD=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
  # configure minio on startup (create buckets, etc)
  # inspired by https://github.com/minio/minio/issues/4769
  # and         https://gist.github.com/haxoza/22afe7cc4a9da7e8bdc09aad393a99cc    
  minio_init:
    # image: minio/mc:RELEASE.2025-04-16T18-13-26Z
    image: minio/mc
    depends_on:
      - minio
    entrypoint:
      - /bin/sh
      - -c
      - |
        echo 'sleeping for 5 seconds while minio starts...'
        sleep 5
        /usr/bin/mc alias set minio http://minio:9000 AKIAIOSFODNN7EXAMPLE wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
        /usr/bin/mc mb minio/cumulus-dev minio/cwbi-airflow-dev
        /usr/bin/mc policy set public minio/cumulus-dev minio/cwbi-airflow-dev
        /usr/bin/mc cp --recursive /media/cumulus/ minio/cumulus-dev/cumulus/
    volumes:
      - ./_volumes/minio:/media
