version: '3'

services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - "8001:8080"
    volumes:
      - ./docs:/usr/share/nginx/html/swagger
    environment:
      API_URL: swagger/apidoc.yaml