version: "3"

networks:
  default:
    name: cumulus-api_default

services: 
  minio:
    image: minio/minio
    environment:
      - MINIO_ROOT_USER=AKIAIOSFODNN7EXAMPLE
      - MINIO_ROOT_PASSWORD=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
  # configure minio on startup (create buckets, etc)
  # inspired by https://github.com/minio/minio/issues/4769
  # and         https://gist.github.com/haxoza/22afe7cc4a9da7e8bdc09aad393a99cc    
  minio_init:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      echo 'sleeping for 10 seconds while minio starts...';
      sleep 10;
      /usr/bin/mc config host add minio http://minio:9000 AKIAIOSFODNN7EXAMPLE wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY;
      /usr/bin/mc mb   minio/cwbi-data-develop   minio/cwbi-data-develop;
      /usr/bin/mc mb   minio/cwbi-data-stable   minio/cwbi-data-stable;
      /usr/bin/mc mb minio/columbia-river;
      /usr/bin/mc policy set public minio/cwbi-data-develop;
      /usr/bin/mc policy set public minio/cwbi-data-stable;
      /usr/bin/mc cp --recursive /media/columbia-river/ minio/columbia-river/;
      /usr/bin/mc cp --recursive /media/cumulus/ minio/cwbi-data-develop/cumulus/;
      exit 0;
      "
    volumes:
      - ./data:/media
