version: "3"

services:
  airflow_init:
    env_file:
      - ./airflow/airflow.env
    image: apache/airflow:master-python3.8
    entrypoint: >
      /bin/sh -c "
      /entrypoint db reset -y;
      /entrypoint db init;
      /entrypoint users create --role Admin --username airflow --email airflow@airflow.com --firstname airflow --lastname airflow --password airflow;
      exit 0
      "
  airflow_scheduler:
    env_file:
      - ./airflow/airflow.env
    image: apache/airflow:master-python3.8
    depends_on:
      - airflow_init
    restart: always
    command: scheduler
    volumes:
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/plugins:/opt/airflow/plugins
  airflow_ui:
    env_file:
      - ./airflow/airflow.env
    image: apache/airflow:master-python3.8
    depends_on:
      - airflow_init
      - airflow_scheduler
    restart: always
    # environment:
    ports:
      - "8000:8080"
    command: webserver
