version: "3"

networks:
  default:
    name: cumulus-api_default
      
services:
  pgclient:
    build:
      context: .
    environment:
        - AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
        - AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
        - AWS_DEFAULT_REGION=us-east-1
        # - AWS_S3_REGION=us-east-1
        - AWS_S3_BUCKET=castle-data-develop
        - AWS_S3_ENDPOINT=http://minio:9000
        - AWS_S3_DISABLE_SSL=True
        - CUMULUS_AWS_S3_FORCE_PATH_STYLE=True
        - PGDATABASE=postgres
        - PGHOST=cumulusdb
        - PGUSER=postgres
        - PGPASSWORD=postgres
        - SCHEMA=cumulus
        - CUMULUS_S3_DB_EXPORT_DIR=cumulus/db_migration
        - MODE=export
    
    # command: ["tail", "-f", "/dev/null"]
    command: /bin/bash -c /app/app.sh

    volumes:
      - ./app:/app